/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var dstore_values_pb = require('../../../dstore/values_pb.js');
var dstore_engine_engine_pb = require('../../../dstore/engine/engine_pb.js');
goog.exportSymbol('proto.dstore.engine.om_GetShippingCost_Pu.Parameters', null, global);
goog.exportSymbol('proto.dstore.engine.om_GetShippingCost_Pu.Response', null, global);
goog.exportSymbol('proto.dstore.engine.om_GetShippingCost_Pu.Response.Row', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dstore.engine.om_GetShippingCost_Pu.Parameters, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.dstore.engine.om_GetShippingCost_Pu.Parameters.displayName = 'proto.dstore.engine.om_GetShippingCost_Pu.Parameters';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.toObject = function(opt_includeInstance) {
  return proto.dstore.engine.om_GetShippingCost_Pu.Parameters.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dstore.engine.om_GetShippingCost_Pu.Parameters} msg The msg instance to transform.
 * @return {!Object}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.toObject = function(includeInstance, msg) {
  var f, obj = {
    shippingTypeId: (f = msg.getShippingTypeId()) && dstore_values_pb.IntegerValue.toObject(includeInstance, f),
    shippingTypeIdNull: msg.getShippingTypeIdNull(),
    currencyId: (f = msg.getCurrencyId()) && dstore_values_pb.IntegerValue.toObject(includeInstance, f),
    currencyIdNull: msg.getCurrencyIdNull(),
    totalBruttoPrice: (f = msg.getTotalBruttoPrice()) && dstore_values_pb.DecimalValue.toObject(includeInstance, f),
    totalBruttoPriceNull: msg.getTotalBruttoPriceNull(),
    totalNettoPrice: (f = msg.getTotalNettoPrice()) && dstore_values_pb.DecimalValue.toObject(includeInstance, f),
    totalNettoPriceNull: msg.getTotalNettoPriceNull(),
    shippingCost: (f = msg.getShippingCost()) && dstore_values_pb.DecimalValue.toObject(includeInstance, f),
    shippingCostNull: msg.getShippingCostNull(),
    shippingCostBrutto: (f = msg.getShippingCostBrutto()) && dstore_values_pb.DecimalValue.toObject(includeInstance, f),
    shippingCostBruttoNull: msg.getShippingCostBruttoNull(),
    selectResult: (f = msg.getSelectResult()) && dstore_values_pb.BooleanValue.toObject(includeInstance, f),
    selectResultNull: msg.getSelectResultNull(),
    date: (f = msg.getDate()) && dstore_values_pb.TimestampValue.toObject(includeInstance, f),
    dateNull: msg.getDateNull(),
    uniqueId: (f = msg.getUniqueId()) && dstore_values_pb.StringValue.toObject(includeInstance, f),
    uniqueIdNull: msg.getUniqueIdNull(),
    personId: (f = msg.getPersonId()) && dstore_values_pb.IntegerValue.toObject(includeInstance, f),
    personIdNull: msg.getPersonIdNull(),
    deliveryPersonId: (f = msg.getDeliveryPersonId()) && dstore_values_pb.IntegerValue.toObject(includeInstance, f),
    deliveryPersonIdNull: msg.getDeliveryPersonIdNull(),
    priceNodeCharacteristicId: (f = msg.getPriceNodeCharacteristicId()) && dstore_values_pb.IntegerValue.toObject(includeInstance, f),
    priceNodeCharacteristicIdNull: msg.getPriceNodeCharacteristicIdNull(),
    paymentTypeId: (f = msg.getPaymentTypeId()) && dstore_values_pb.IntegerValue.toObject(includeInstance, f),
    paymentTypeIdNull: msg.getPaymentTypeIdNull()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dstore.engine.om_GetShippingCost_Pu.Parameters}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dstore.engine.om_GetShippingCost_Pu.Parameters;
  return proto.dstore.engine.om_GetShippingCost_Pu.Parameters.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dstore.engine.om_GetShippingCost_Pu.Parameters} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dstore.engine.om_GetShippingCost_Pu.Parameters}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new dstore_values_pb.IntegerValue;
      reader.readMessage(value,dstore_values_pb.IntegerValue.deserializeBinaryFromReader);
      msg.setShippingTypeId(value);
      break;
    case 1001:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShippingTypeIdNull(value);
      break;
    case 2:
      var value = new dstore_values_pb.IntegerValue;
      reader.readMessage(value,dstore_values_pb.IntegerValue.deserializeBinaryFromReader);
      msg.setCurrencyId(value);
      break;
    case 1002:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCurrencyIdNull(value);
      break;
    case 3:
      var value = new dstore_values_pb.DecimalValue;
      reader.readMessage(value,dstore_values_pb.DecimalValue.deserializeBinaryFromReader);
      msg.setTotalBruttoPrice(value);
      break;
    case 1003:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTotalBruttoPriceNull(value);
      break;
    case 4:
      var value = new dstore_values_pb.DecimalValue;
      reader.readMessage(value,dstore_values_pb.DecimalValue.deserializeBinaryFromReader);
      msg.setTotalNettoPrice(value);
      break;
    case 1004:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTotalNettoPriceNull(value);
      break;
    case 5:
      var value = new dstore_values_pb.DecimalValue;
      reader.readMessage(value,dstore_values_pb.DecimalValue.deserializeBinaryFromReader);
      msg.setShippingCost(value);
      break;
    case 1005:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShippingCostNull(value);
      break;
    case 6:
      var value = new dstore_values_pb.DecimalValue;
      reader.readMessage(value,dstore_values_pb.DecimalValue.deserializeBinaryFromReader);
      msg.setShippingCostBrutto(value);
      break;
    case 1006:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShippingCostBruttoNull(value);
      break;
    case 7:
      var value = new dstore_values_pb.BooleanValue;
      reader.readMessage(value,dstore_values_pb.BooleanValue.deserializeBinaryFromReader);
      msg.setSelectResult(value);
      break;
    case 1007:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSelectResultNull(value);
      break;
    case 8:
      var value = new dstore_values_pb.TimestampValue;
      reader.readMessage(value,dstore_values_pb.TimestampValue.deserializeBinaryFromReader);
      msg.setDate(value);
      break;
    case 1008:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDateNull(value);
      break;
    case 9:
      var value = new dstore_values_pb.StringValue;
      reader.readMessage(value,dstore_values_pb.StringValue.deserializeBinaryFromReader);
      msg.setUniqueId(value);
      break;
    case 1009:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setUniqueIdNull(value);
      break;
    case 10:
      var value = new dstore_values_pb.IntegerValue;
      reader.readMessage(value,dstore_values_pb.IntegerValue.deserializeBinaryFromReader);
      msg.setPersonId(value);
      break;
    case 1010:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPersonIdNull(value);
      break;
    case 11:
      var value = new dstore_values_pb.IntegerValue;
      reader.readMessage(value,dstore_values_pb.IntegerValue.deserializeBinaryFromReader);
      msg.setDeliveryPersonId(value);
      break;
    case 1011:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDeliveryPersonIdNull(value);
      break;
    case 12:
      var value = new dstore_values_pb.IntegerValue;
      reader.readMessage(value,dstore_values_pb.IntegerValue.deserializeBinaryFromReader);
      msg.setPriceNodeCharacteristicId(value);
      break;
    case 1012:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPriceNodeCharacteristicIdNull(value);
      break;
    case 13:
      var value = new dstore_values_pb.IntegerValue;
      reader.readMessage(value,dstore_values_pb.IntegerValue.deserializeBinaryFromReader);
      msg.setPaymentTypeId(value);
      break;
    case 1013:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPaymentTypeIdNull(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.dstore.engine.om_GetShippingCost_Pu.Parameters} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getShippingTypeId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      dstore_values_pb.IntegerValue.serializeBinaryToWriter
    );
  }
  f = this.getShippingTypeIdNull();
  if (f) {
    writer.writeBool(
      1001,
      f
    );
  }
  f = this.getCurrencyId();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      dstore_values_pb.IntegerValue.serializeBinaryToWriter
    );
  }
  f = this.getCurrencyIdNull();
  if (f) {
    writer.writeBool(
      1002,
      f
    );
  }
  f = this.getTotalBruttoPrice();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      dstore_values_pb.DecimalValue.serializeBinaryToWriter
    );
  }
  f = this.getTotalBruttoPriceNull();
  if (f) {
    writer.writeBool(
      1003,
      f
    );
  }
  f = this.getTotalNettoPrice();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      dstore_values_pb.DecimalValue.serializeBinaryToWriter
    );
  }
  f = this.getTotalNettoPriceNull();
  if (f) {
    writer.writeBool(
      1004,
      f
    );
  }
  f = this.getShippingCost();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      dstore_values_pb.DecimalValue.serializeBinaryToWriter
    );
  }
  f = this.getShippingCostNull();
  if (f) {
    writer.writeBool(
      1005,
      f
    );
  }
  f = this.getShippingCostBrutto();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      dstore_values_pb.DecimalValue.serializeBinaryToWriter
    );
  }
  f = this.getShippingCostBruttoNull();
  if (f) {
    writer.writeBool(
      1006,
      f
    );
  }
  f = this.getSelectResult();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      dstore_values_pb.BooleanValue.serializeBinaryToWriter
    );
  }
  f = this.getSelectResultNull();
  if (f) {
    writer.writeBool(
      1007,
      f
    );
  }
  f = this.getDate();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      dstore_values_pb.TimestampValue.serializeBinaryToWriter
    );
  }
  f = this.getDateNull();
  if (f) {
    writer.writeBool(
      1008,
      f
    );
  }
  f = this.getUniqueId();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      dstore_values_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = this.getUniqueIdNull();
  if (f) {
    writer.writeBool(
      1009,
      f
    );
  }
  f = this.getPersonId();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      dstore_values_pb.IntegerValue.serializeBinaryToWriter
    );
  }
  f = this.getPersonIdNull();
  if (f) {
    writer.writeBool(
      1010,
      f
    );
  }
  f = this.getDeliveryPersonId();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      dstore_values_pb.IntegerValue.serializeBinaryToWriter
    );
  }
  f = this.getDeliveryPersonIdNull();
  if (f) {
    writer.writeBool(
      1011,
      f
    );
  }
  f = this.getPriceNodeCharacteristicId();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      dstore_values_pb.IntegerValue.serializeBinaryToWriter
    );
  }
  f = this.getPriceNodeCharacteristicIdNull();
  if (f) {
    writer.writeBool(
      1012,
      f
    );
  }
  f = this.getPaymentTypeId();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      dstore_values_pb.IntegerValue.serializeBinaryToWriter
    );
  }
  f = this.getPaymentTypeIdNull();
  if (f) {
    writer.writeBool(
      1013,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.dstore.engine.om_GetShippingCost_Pu.Parameters} The clone.
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.cloneMessage = function() {
  return /** @type {!proto.dstore.engine.om_GetShippingCost_Pu.Parameters} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional dstore.values.IntegerValue shipping_type_id = 1;
 * @return {proto.dstore.values.IntegerValue}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getShippingTypeId = function() {
  return /** @type{proto.dstore.values.IntegerValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.IntegerValue, 1));
};


/** @param {proto.dstore.values.IntegerValue|undefined} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setShippingTypeId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.clearShippingTypeId = function() {
  this.setShippingTypeId(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.hasShippingTypeId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool shipping_type_id_null = 1001;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getShippingTypeIdNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 1001, false));
};


/** @param {boolean} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setShippingTypeIdNull = function(value) {
  jspb.Message.setField(this, 1001, value);
};


/**
 * optional dstore.values.IntegerValue currency_id = 2;
 * @return {proto.dstore.values.IntegerValue}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getCurrencyId = function() {
  return /** @type{proto.dstore.values.IntegerValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.IntegerValue, 2));
};


/** @param {proto.dstore.values.IntegerValue|undefined} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setCurrencyId = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.clearCurrencyId = function() {
  this.setCurrencyId(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.hasCurrencyId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool currency_id_null = 1002;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getCurrencyIdNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 1002, false));
};


/** @param {boolean} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setCurrencyIdNull = function(value) {
  jspb.Message.setField(this, 1002, value);
};


/**
 * optional dstore.values.DecimalValue total_brutto_price = 3;
 * @return {proto.dstore.values.DecimalValue}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getTotalBruttoPrice = function() {
  return /** @type{proto.dstore.values.DecimalValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.DecimalValue, 3));
};


/** @param {proto.dstore.values.DecimalValue|undefined} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setTotalBruttoPrice = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.clearTotalBruttoPrice = function() {
  this.setTotalBruttoPrice(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.hasTotalBruttoPrice = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional bool total_brutto_price_null = 1003;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getTotalBruttoPriceNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 1003, false));
};


/** @param {boolean} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setTotalBruttoPriceNull = function(value) {
  jspb.Message.setField(this, 1003, value);
};


/**
 * optional dstore.values.DecimalValue total_netto_price = 4;
 * @return {proto.dstore.values.DecimalValue}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getTotalNettoPrice = function() {
  return /** @type{proto.dstore.values.DecimalValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.DecimalValue, 4));
};


/** @param {proto.dstore.values.DecimalValue|undefined} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setTotalNettoPrice = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.clearTotalNettoPrice = function() {
  this.setTotalNettoPrice(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.hasTotalNettoPrice = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bool total_netto_price_null = 1004;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getTotalNettoPriceNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 1004, false));
};


/** @param {boolean} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setTotalNettoPriceNull = function(value) {
  jspb.Message.setField(this, 1004, value);
};


/**
 * optional dstore.values.DecimalValue shipping_cost = 5;
 * @return {proto.dstore.values.DecimalValue}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getShippingCost = function() {
  return /** @type{proto.dstore.values.DecimalValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.DecimalValue, 5));
};


/** @param {proto.dstore.values.DecimalValue|undefined} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setShippingCost = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.clearShippingCost = function() {
  this.setShippingCost(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.hasShippingCost = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bool shipping_cost_null = 1005;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getShippingCostNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 1005, false));
};


/** @param {boolean} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setShippingCostNull = function(value) {
  jspb.Message.setField(this, 1005, value);
};


/**
 * optional dstore.values.DecimalValue shipping_cost_brutto = 6;
 * @return {proto.dstore.values.DecimalValue}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getShippingCostBrutto = function() {
  return /** @type{proto.dstore.values.DecimalValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.DecimalValue, 6));
};


/** @param {proto.dstore.values.DecimalValue|undefined} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setShippingCostBrutto = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.clearShippingCostBrutto = function() {
  this.setShippingCostBrutto(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.hasShippingCostBrutto = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional bool shipping_cost_brutto_null = 1006;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getShippingCostBruttoNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 1006, false));
};


/** @param {boolean} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setShippingCostBruttoNull = function(value) {
  jspb.Message.setField(this, 1006, value);
};


/**
 * optional dstore.values.BooleanValue select_result = 7;
 * @return {proto.dstore.values.BooleanValue}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getSelectResult = function() {
  return /** @type{proto.dstore.values.BooleanValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.BooleanValue, 7));
};


/** @param {proto.dstore.values.BooleanValue|undefined} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setSelectResult = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.clearSelectResult = function() {
  this.setSelectResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.hasSelectResult = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional bool select_result_null = 1007;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getSelectResultNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 1007, false));
};


/** @param {boolean} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setSelectResultNull = function(value) {
  jspb.Message.setField(this, 1007, value);
};


/**
 * optional dstore.values.TimestampValue date = 8;
 * @return {proto.dstore.values.TimestampValue}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getDate = function() {
  return /** @type{proto.dstore.values.TimestampValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.TimestampValue, 8));
};


/** @param {proto.dstore.values.TimestampValue|undefined} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setDate = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.clearDate = function() {
  this.setDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.hasDate = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional bool date_null = 1008;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getDateNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 1008, false));
};


/** @param {boolean} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setDateNull = function(value) {
  jspb.Message.setField(this, 1008, value);
};


/**
 * optional dstore.values.StringValue unique_id = 9;
 * @return {proto.dstore.values.StringValue}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getUniqueId = function() {
  return /** @type{proto.dstore.values.StringValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.StringValue, 9));
};


/** @param {proto.dstore.values.StringValue|undefined} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setUniqueId = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.clearUniqueId = function() {
  this.setUniqueId(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.hasUniqueId = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional bool unique_id_null = 1009;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getUniqueIdNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 1009, false));
};


/** @param {boolean} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setUniqueIdNull = function(value) {
  jspb.Message.setField(this, 1009, value);
};


/**
 * optional dstore.values.IntegerValue person_id = 10;
 * @return {proto.dstore.values.IntegerValue}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getPersonId = function() {
  return /** @type{proto.dstore.values.IntegerValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.IntegerValue, 10));
};


/** @param {proto.dstore.values.IntegerValue|undefined} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setPersonId = function(value) {
  jspb.Message.setWrapperField(this, 10, value);
};


proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.clearPersonId = function() {
  this.setPersonId(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.hasPersonId = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional bool person_id_null = 1010;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getPersonIdNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 1010, false));
};


/** @param {boolean} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setPersonIdNull = function(value) {
  jspb.Message.setField(this, 1010, value);
};


/**
 * optional dstore.values.IntegerValue delivery_person_id = 11;
 * @return {proto.dstore.values.IntegerValue}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getDeliveryPersonId = function() {
  return /** @type{proto.dstore.values.IntegerValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.IntegerValue, 11));
};


/** @param {proto.dstore.values.IntegerValue|undefined} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setDeliveryPersonId = function(value) {
  jspb.Message.setWrapperField(this, 11, value);
};


proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.clearDeliveryPersonId = function() {
  this.setDeliveryPersonId(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.hasDeliveryPersonId = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional bool delivery_person_id_null = 1011;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getDeliveryPersonIdNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 1011, false));
};


/** @param {boolean} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setDeliveryPersonIdNull = function(value) {
  jspb.Message.setField(this, 1011, value);
};


/**
 * optional dstore.values.IntegerValue price_node_characteristic_id = 12;
 * @return {proto.dstore.values.IntegerValue}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getPriceNodeCharacteristicId = function() {
  return /** @type{proto.dstore.values.IntegerValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.IntegerValue, 12));
};


/** @param {proto.dstore.values.IntegerValue|undefined} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setPriceNodeCharacteristicId = function(value) {
  jspb.Message.setWrapperField(this, 12, value);
};


proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.clearPriceNodeCharacteristicId = function() {
  this.setPriceNodeCharacteristicId(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.hasPriceNodeCharacteristicId = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional bool price_node_characteristic_id_null = 1012;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getPriceNodeCharacteristicIdNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 1012, false));
};


/** @param {boolean} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setPriceNodeCharacteristicIdNull = function(value) {
  jspb.Message.setField(this, 1012, value);
};


/**
 * optional dstore.values.IntegerValue payment_type_id = 13;
 * @return {proto.dstore.values.IntegerValue}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getPaymentTypeId = function() {
  return /** @type{proto.dstore.values.IntegerValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.IntegerValue, 13));
};


/** @param {proto.dstore.values.IntegerValue|undefined} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setPaymentTypeId = function(value) {
  jspb.Message.setWrapperField(this, 13, value);
};


proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.clearPaymentTypeId = function() {
  this.setPaymentTypeId(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.hasPaymentTypeId = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional bool payment_type_id_null = 1013;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.getPaymentTypeIdNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 1013, false));
};


/** @param {boolean} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Parameters.prototype.setPaymentTypeIdNull = function(value) {
  jspb.Message.setField(this, 1013, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.dstore.engine.om_GetShippingCost_Pu.Response.repeatedFields_, null);
};
goog.inherits(proto.dstore.engine.om_GetShippingCost_Pu.Response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.dstore.engine.om_GetShippingCost_Pu.Response.displayName = 'proto.dstore.engine.om_GetShippingCost_Pu.Response';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.repeatedFields_ = [2,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.toObject = function(opt_includeInstance) {
  return proto.dstore.engine.om_GetShippingCost_Pu.Response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dstore.engine.om_GetShippingCost_Pu.Response} msg The msg instance to transform.
 * @return {!Object}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.toObject = function(includeInstance, msg) {
  var f, obj = {
    metaInformationList: jspb.Message.toObjectList(msg.getMetaInformationList(),
    dstore_engine_engine_pb.MetaInformation.toObject, includeInstance),
    messageList: jspb.Message.toObjectList(msg.getMessageList(),
    dstore_engine_engine_pb.Message.toObject, includeInstance),
    rowList: jspb.Message.toObjectList(msg.getRowList(),
    proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.toObject, includeInstance),
    shippingCost: (f = msg.getShippingCost()) && dstore_values_pb.DecimalValue.toObject(includeInstance, f),
    shippingCostBrutto: (f = msg.getShippingCostBrutto()) && dstore_values_pb.DecimalValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dstore.engine.om_GetShippingCost_Pu.Response}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dstore.engine.om_GetShippingCost_Pu.Response;
  return proto.dstore.engine.om_GetShippingCost_Pu.Response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dstore.engine.om_GetShippingCost_Pu.Response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dstore.engine.om_GetShippingCost_Pu.Response}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new dstore_engine_engine_pb.MetaInformation;
      reader.readMessage(value,dstore_engine_engine_pb.MetaInformation.deserializeBinaryFromReader);
      msg.getMetaInformationList().push(value);
      msg.setMetaInformationList(msg.getMetaInformationList());
      break;
    case 3:
      var value = new dstore_engine_engine_pb.Message;
      reader.readMessage(value,dstore_engine_engine_pb.Message.deserializeBinaryFromReader);
      msg.getMessageList().push(value);
      msg.setMessageList(msg.getMessageList());
      break;
    case 4:
      var value = new proto.dstore.engine.om_GetShippingCost_Pu.Response.Row;
      reader.readMessage(value,proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.deserializeBinaryFromReader);
      msg.getRowList().push(value);
      msg.setRowList(msg.getRowList());
      break;
    case 101:
      var value = new dstore_values_pb.DecimalValue;
      reader.readMessage(value,dstore_values_pb.DecimalValue.deserializeBinaryFromReader);
      msg.setShippingCost(value);
      break;
    case 102:
      var value = new dstore_values_pb.DecimalValue;
      reader.readMessage(value,dstore_values_pb.DecimalValue.deserializeBinaryFromReader);
      msg.setShippingCostBrutto(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.dstore.engine.om_GetShippingCost_Pu.Response} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getMetaInformationList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      dstore_engine_engine_pb.MetaInformation.serializeBinaryToWriter
    );
  }
  f = this.getMessageList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      dstore_engine_engine_pb.Message.serializeBinaryToWriter
    );
  }
  f = this.getRowList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.serializeBinaryToWriter
    );
  }
  f = this.getShippingCost();
  if (f != null) {
    writer.writeMessage(
      101,
      f,
      dstore_values_pb.DecimalValue.serializeBinaryToWriter
    );
  }
  f = this.getShippingCostBrutto();
  if (f != null) {
    writer.writeMessage(
      102,
      f,
      dstore_values_pb.DecimalValue.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.dstore.engine.om_GetShippingCost_Pu.Response} The clone.
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.cloneMessage = function() {
  return /** @type {!proto.dstore.engine.om_GetShippingCost_Pu.Response} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated dstore.engine.MetaInformation meta_information = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.dstore.engine.MetaInformation>}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.getMetaInformationList = function() {
  return /** @type{!Array.<!proto.dstore.engine.MetaInformation>} */ (
    jspb.Message.getRepeatedWrapperField(this, dstore_engine_engine_pb.MetaInformation, 2));
};


/** @param {Array.<!proto.dstore.engine.MetaInformation>} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.setMetaInformationList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.clearMetaInformationList = function() {
  this.setMetaInformationList([]);
};


/**
 * repeated dstore.engine.Message message = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.dstore.engine.Message>}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.getMessageList = function() {
  return /** @type{!Array.<!proto.dstore.engine.Message>} */ (
    jspb.Message.getRepeatedWrapperField(this, dstore_engine_engine_pb.Message, 3));
};


/** @param {Array.<!proto.dstore.engine.Message>} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.setMessageList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.clearMessageList = function() {
  this.setMessageList([]);
};


/**
 * repeated Row row = 4;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.dstore.engine.om_GetShippingCost_Pu.Response.Row>}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.getRowList = function() {
  return /** @type{!Array.<!proto.dstore.engine.om_GetShippingCost_Pu.Response.Row>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.dstore.engine.om_GetShippingCost_Pu.Response.Row, 4));
};


/** @param {Array.<!proto.dstore.engine.om_GetShippingCost_Pu.Response.Row>} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.setRowList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.clearRowList = function() {
  this.setRowList([]);
};


/**
 * optional dstore.values.DecimalValue shipping_cost = 101;
 * @return {proto.dstore.values.DecimalValue}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.getShippingCost = function() {
  return /** @type{proto.dstore.values.DecimalValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.DecimalValue, 101));
};


/** @param {proto.dstore.values.DecimalValue|undefined} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.setShippingCost = function(value) {
  jspb.Message.setWrapperField(this, 101, value);
};


proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.clearShippingCost = function() {
  this.setShippingCost(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.hasShippingCost = function() {
  return jspb.Message.getField(this, 101) != null;
};


/**
 * optional dstore.values.DecimalValue shipping_cost_brutto = 102;
 * @return {proto.dstore.values.DecimalValue}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.getShippingCostBrutto = function() {
  return /** @type{proto.dstore.values.DecimalValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.DecimalValue, 102));
};


/** @param {proto.dstore.values.DecimalValue|undefined} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.setShippingCostBrutto = function(value) {
  jspb.Message.setWrapperField(this, 102, value);
};


proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.clearShippingCostBrutto = function() {
  this.setShippingCostBrutto(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.prototype.hasShippingCostBrutto = function() {
  return jspb.Message.getField(this, 102) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.Row = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dstore.engine.om_GetShippingCost_Pu.Response.Row, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.displayName = 'proto.dstore.engine.om_GetShippingCost_Pu.Response.Row';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.prototype.toObject = function(opt_includeInstance) {
  return proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dstore.engine.om_GetShippingCost_Pu.Response.Row} msg The msg instance to transform.
 * @return {!Object}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.toObject = function(includeInstance, msg) {
  var f, obj = {
    rowId: msg.getRowId(),
    shippingCost: (f = msg.getShippingCost()) && dstore_values_pb.DecimalValue.toObject(includeInstance, f),
    shippingCostBrutto: (f = msg.getShippingCostBrutto()) && dstore_values_pb.DecimalValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dstore.engine.om_GetShippingCost_Pu.Response.Row}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dstore.engine.om_GetShippingCost_Pu.Response.Row;
  return proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dstore.engine.om_GetShippingCost_Pu.Response.Row} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dstore.engine.om_GetShippingCost_Pu.Response.Row}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 10000:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRowId(value);
      break;
    case 10001:
      var value = new dstore_values_pb.DecimalValue;
      reader.readMessage(value,dstore_values_pb.DecimalValue.deserializeBinaryFromReader);
      msg.setShippingCost(value);
      break;
    case 10002:
      var value = new dstore_values_pb.DecimalValue;
      reader.readMessage(value,dstore_values_pb.DecimalValue.deserializeBinaryFromReader);
      msg.setShippingCostBrutto(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.dstore.engine.om_GetShippingCost_Pu.Response.Row} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getRowId();
  if (f !== 0) {
    writer.writeInt32(
      10000,
      f
    );
  }
  f = this.getShippingCost();
  if (f != null) {
    writer.writeMessage(
      10001,
      f,
      dstore_values_pb.DecimalValue.serializeBinaryToWriter
    );
  }
  f = this.getShippingCostBrutto();
  if (f != null) {
    writer.writeMessage(
      10002,
      f,
      dstore_values_pb.DecimalValue.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.dstore.engine.om_GetShippingCost_Pu.Response.Row} The clone.
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.prototype.cloneMessage = function() {
  return /** @type {!proto.dstore.engine.om_GetShippingCost_Pu.Response.Row} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 row_id = 10000;
 * @return {number}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.prototype.getRowId = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 10000, 0));
};


/** @param {number} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.prototype.setRowId = function(value) {
  jspb.Message.setField(this, 10000, value);
};


/**
 * optional dstore.values.DecimalValue shipping_cost = 10001;
 * @return {proto.dstore.values.DecimalValue}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.prototype.getShippingCost = function() {
  return /** @type{proto.dstore.values.DecimalValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.DecimalValue, 10001));
};


/** @param {proto.dstore.values.DecimalValue|undefined} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.prototype.setShippingCost = function(value) {
  jspb.Message.setWrapperField(this, 10001, value);
};


proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.prototype.clearShippingCost = function() {
  this.setShippingCost(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.prototype.hasShippingCost = function() {
  return jspb.Message.getField(this, 10001) != null;
};


/**
 * optional dstore.values.DecimalValue shipping_cost_brutto = 10002;
 * @return {proto.dstore.values.DecimalValue}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.prototype.getShippingCostBrutto = function() {
  return /** @type{proto.dstore.values.DecimalValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.DecimalValue, 10002));
};


/** @param {proto.dstore.values.DecimalValue|undefined} value  */
proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.prototype.setShippingCostBrutto = function(value) {
  jspb.Message.setWrapperField(this, 10002, value);
};


proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.prototype.clearShippingCostBrutto = function() {
  this.setShippingCostBrutto(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.dstore.engine.om_GetShippingCost_Pu.Response.Row.prototype.hasShippingCostBrutto = function() {
  return jspb.Message.getField(this, 10002) != null;
};


goog.object.extend(exports, proto.dstore.engine.om_GetShippingCost_Pu);
