/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var dstore_values_pb = require('../../../dstore/values_pb.js');
var dstore_engine_message_pb = require('../../../dstore/engine/message_pb.js');
var dstore_engine_metainformation_pb = require('../../../dstore/engine/metainformation_pb.js');
goog.exportSymbol('proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters', null, global);
goog.exportSymbol('proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response', null, global);
goog.exportSymbol('proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.displayName = 'proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.toObject = function(opt_includeInstance) {
  return proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters} msg The msg instance to transform.
 * @return {!Object}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.toObject = function(includeInstance, msg) {
  var f, obj = {
    sortOrder1: (f = msg.getSortOrder1()) && dstore_values_pb.booleanValue.toObject(includeInstance, f),
    sortOrder1Null: jspb.Message.getFieldWithDefault(msg, 1001, false),
    sortOrder2: (f = msg.getSortOrder2()) && dstore_values_pb.booleanValue.toObject(includeInstance, f),
    sortOrder2Null: jspb.Message.getFieldWithDefault(msg, 1002, false),
    sortOrder3: (f = msg.getSortOrder3()) && dstore_values_pb.booleanValue.toObject(includeInstance, f),
    sortOrder3Null: jspb.Message.getFieldWithDefault(msg, 1003, false),
    outputCharacteristicIds: (f = msg.getOutputCharacteristicIds()) && dstore_values_pb.stringValue.toObject(includeInstance, f),
    outputCharacteristicIdsNull: jspb.Message.getFieldWithDefault(msg, 1004, false),
    count: (f = msg.getCount()) && dstore_values_pb.integerValue.toObject(includeInstance, f),
    countNull: jspb.Message.getFieldWithDefault(msg, 1005, false),
    personTypeId: (f = msg.getPersonTypeId()) && dstore_values_pb.integerValue.toObject(includeInstance, f),
    personTypeIdNull: jspb.Message.getFieldWithDefault(msg, 1006, false),
    lastValues: (f = msg.getLastValues()) && dstore_values_pb.stringValue.toObject(includeInstance, f),
    lastValuesNull: jspb.Message.getFieldWithDefault(msg, 1007, false),
    lastPersonId: (f = msg.getLastPersonId()) && dstore_values_pb.integerValue.toObject(includeInstance, f),
    lastPersonIdNull: jspb.Message.getFieldWithDefault(msg, 1008, false),
    next: (f = msg.getNext()) && dstore_values_pb.booleanValue.toObject(includeInstance, f),
    nextNull: jspb.Message.getFieldWithDefault(msg, 1009, false),
    rowNumber: (f = msg.getRowNumber()) && dstore_values_pb.integerValue.toObject(includeInstance, f),
    rowNumberNull: jspb.Message.getFieldWithDefault(msg, 1010, false),
    groupId: (f = msg.getGroupId()) && dstore_values_pb.integerValue.toObject(includeInstance, f),
    groupIdNull: jspb.Message.getFieldWithDefault(msg, 1011, false),
    characteristicIdList: (f = msg.getCharacteristicIdList()) && dstore_values_pb.stringValue.toObject(includeInstance, f),
    characteristicIdListNull: jspb.Message.getFieldWithDefault(msg, 1012, false),
    conditionList: (f = msg.getConditionList()) && dstore_values_pb.stringValue.toObject(includeInstance, f),
    conditionListNull: jspb.Message.getFieldWithDefault(msg, 1013, false),
    country: (f = msg.getCountry()) && dstore_values_pb.stringValue.toObject(includeInstance, f),
    countryNull: jspb.Message.getFieldWithDefault(msg, 1014, false),
    outputIntoOneId: (f = msg.getOutputIntoOneId()) && dstore_values_pb.integerValue.toObject(includeInstance, f),
    outputIntoOneIdNull: jspb.Message.getFieldWithDefault(msg, 1015, false),
    separatorInLastValues: (f = msg.getSeparatorInLastValues()) && dstore_values_pb.stringValue.toObject(includeInstance, f),
    separatorInLastValuesNull: jspb.Message.getFieldWithDefault(msg, 1016, false),
    separatorInConditionList: (f = msg.getSeparatorInConditionList()) && dstore_values_pb.stringValue.toObject(includeInstance, f),
    separatorInConditionListNull: jspb.Message.getFieldWithDefault(msg, 1017, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters;
  return proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new dstore_values_pb.booleanValue;
      reader.readMessage(value,dstore_values_pb.booleanValue.deserializeBinaryFromReader);
      msg.setSortOrder1(value);
      break;
    case 1001:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSortOrder1Null(value);
      break;
    case 2:
      var value = new dstore_values_pb.booleanValue;
      reader.readMessage(value,dstore_values_pb.booleanValue.deserializeBinaryFromReader);
      msg.setSortOrder2(value);
      break;
    case 1002:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSortOrder2Null(value);
      break;
    case 3:
      var value = new dstore_values_pb.booleanValue;
      reader.readMessage(value,dstore_values_pb.booleanValue.deserializeBinaryFromReader);
      msg.setSortOrder3(value);
      break;
    case 1003:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSortOrder3Null(value);
      break;
    case 4:
      var value = new dstore_values_pb.stringValue;
      reader.readMessage(value,dstore_values_pb.stringValue.deserializeBinaryFromReader);
      msg.setOutputCharacteristicIds(value);
      break;
    case 1004:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOutputCharacteristicIdsNull(value);
      break;
    case 5:
      var value = new dstore_values_pb.integerValue;
      reader.readMessage(value,dstore_values_pb.integerValue.deserializeBinaryFromReader);
      msg.setCount(value);
      break;
    case 1005:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCountNull(value);
      break;
    case 6:
      var value = new dstore_values_pb.integerValue;
      reader.readMessage(value,dstore_values_pb.integerValue.deserializeBinaryFromReader);
      msg.setPersonTypeId(value);
      break;
    case 1006:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPersonTypeIdNull(value);
      break;
    case 7:
      var value = new dstore_values_pb.stringValue;
      reader.readMessage(value,dstore_values_pb.stringValue.deserializeBinaryFromReader);
      msg.setLastValues(value);
      break;
    case 1007:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setLastValuesNull(value);
      break;
    case 8:
      var value = new dstore_values_pb.integerValue;
      reader.readMessage(value,dstore_values_pb.integerValue.deserializeBinaryFromReader);
      msg.setLastPersonId(value);
      break;
    case 1008:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setLastPersonIdNull(value);
      break;
    case 9:
      var value = new dstore_values_pb.booleanValue;
      reader.readMessage(value,dstore_values_pb.booleanValue.deserializeBinaryFromReader);
      msg.setNext(value);
      break;
    case 1009:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNextNull(value);
      break;
    case 10:
      var value = new dstore_values_pb.integerValue;
      reader.readMessage(value,dstore_values_pb.integerValue.deserializeBinaryFromReader);
      msg.setRowNumber(value);
      break;
    case 1010:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRowNumberNull(value);
      break;
    case 11:
      var value = new dstore_values_pb.integerValue;
      reader.readMessage(value,dstore_values_pb.integerValue.deserializeBinaryFromReader);
      msg.setGroupId(value);
      break;
    case 1011:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setGroupIdNull(value);
      break;
    case 12:
      var value = new dstore_values_pb.stringValue;
      reader.readMessage(value,dstore_values_pb.stringValue.deserializeBinaryFromReader);
      msg.setCharacteristicIdList(value);
      break;
    case 1012:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCharacteristicIdListNull(value);
      break;
    case 13:
      var value = new dstore_values_pb.stringValue;
      reader.readMessage(value,dstore_values_pb.stringValue.deserializeBinaryFromReader);
      msg.setConditionList(value);
      break;
    case 1013:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setConditionListNull(value);
      break;
    case 14:
      var value = new dstore_values_pb.stringValue;
      reader.readMessage(value,dstore_values_pb.stringValue.deserializeBinaryFromReader);
      msg.setCountry(value);
      break;
    case 1014:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCountryNull(value);
      break;
    case 15:
      var value = new dstore_values_pb.integerValue;
      reader.readMessage(value,dstore_values_pb.integerValue.deserializeBinaryFromReader);
      msg.setOutputIntoOneId(value);
      break;
    case 1015:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOutputIntoOneIdNull(value);
      break;
    case 16:
      var value = new dstore_values_pb.stringValue;
      reader.readMessage(value,dstore_values_pb.stringValue.deserializeBinaryFromReader);
      msg.setSeparatorInLastValues(value);
      break;
    case 1016:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSeparatorInLastValuesNull(value);
      break;
    case 17:
      var value = new dstore_values_pb.stringValue;
      reader.readMessage(value,dstore_values_pb.stringValue.deserializeBinaryFromReader);
      msg.setSeparatorInConditionList(value);
      break;
    case 1017:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSeparatorInConditionListNull(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getSortOrder1();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      dstore_values_pb.booleanValue.serializeBinaryToWriter
    );
  }
  f = this.getSortOrder1Null();
  if (f) {
    writer.writeBool(
      1001,
      f
    );
  }
  f = this.getSortOrder2();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      dstore_values_pb.booleanValue.serializeBinaryToWriter
    );
  }
  f = this.getSortOrder2Null();
  if (f) {
    writer.writeBool(
      1002,
      f
    );
  }
  f = this.getSortOrder3();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      dstore_values_pb.booleanValue.serializeBinaryToWriter
    );
  }
  f = this.getSortOrder3Null();
  if (f) {
    writer.writeBool(
      1003,
      f
    );
  }
  f = this.getOutputCharacteristicIds();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      dstore_values_pb.stringValue.serializeBinaryToWriter
    );
  }
  f = this.getOutputCharacteristicIdsNull();
  if (f) {
    writer.writeBool(
      1004,
      f
    );
  }
  f = this.getCount();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      dstore_values_pb.integerValue.serializeBinaryToWriter
    );
  }
  f = this.getCountNull();
  if (f) {
    writer.writeBool(
      1005,
      f
    );
  }
  f = this.getPersonTypeId();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      dstore_values_pb.integerValue.serializeBinaryToWriter
    );
  }
  f = this.getPersonTypeIdNull();
  if (f) {
    writer.writeBool(
      1006,
      f
    );
  }
  f = this.getLastValues();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      dstore_values_pb.stringValue.serializeBinaryToWriter
    );
  }
  f = this.getLastValuesNull();
  if (f) {
    writer.writeBool(
      1007,
      f
    );
  }
  f = this.getLastPersonId();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      dstore_values_pb.integerValue.serializeBinaryToWriter
    );
  }
  f = this.getLastPersonIdNull();
  if (f) {
    writer.writeBool(
      1008,
      f
    );
  }
  f = this.getNext();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      dstore_values_pb.booleanValue.serializeBinaryToWriter
    );
  }
  f = this.getNextNull();
  if (f) {
    writer.writeBool(
      1009,
      f
    );
  }
  f = this.getRowNumber();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      dstore_values_pb.integerValue.serializeBinaryToWriter
    );
  }
  f = this.getRowNumberNull();
  if (f) {
    writer.writeBool(
      1010,
      f
    );
  }
  f = this.getGroupId();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      dstore_values_pb.integerValue.serializeBinaryToWriter
    );
  }
  f = this.getGroupIdNull();
  if (f) {
    writer.writeBool(
      1011,
      f
    );
  }
  f = this.getCharacteristicIdList();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      dstore_values_pb.stringValue.serializeBinaryToWriter
    );
  }
  f = this.getCharacteristicIdListNull();
  if (f) {
    writer.writeBool(
      1012,
      f
    );
  }
  f = this.getConditionList();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      dstore_values_pb.stringValue.serializeBinaryToWriter
    );
  }
  f = this.getConditionListNull();
  if (f) {
    writer.writeBool(
      1013,
      f
    );
  }
  f = this.getCountry();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      dstore_values_pb.stringValue.serializeBinaryToWriter
    );
  }
  f = this.getCountryNull();
  if (f) {
    writer.writeBool(
      1014,
      f
    );
  }
  f = this.getOutputIntoOneId();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      dstore_values_pb.integerValue.serializeBinaryToWriter
    );
  }
  f = this.getOutputIntoOneIdNull();
  if (f) {
    writer.writeBool(
      1015,
      f
    );
  }
  f = this.getSeparatorInLastValues();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      dstore_values_pb.stringValue.serializeBinaryToWriter
    );
  }
  f = this.getSeparatorInLastValuesNull();
  if (f) {
    writer.writeBool(
      1016,
      f
    );
  }
  f = this.getSeparatorInConditionList();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      dstore_values_pb.stringValue.serializeBinaryToWriter
    );
  }
  f = this.getSeparatorInConditionListNull();
  if (f) {
    writer.writeBool(
      1017,
      f
    );
  }
};


/**
 * optional dstore.values.booleanValue sort_order1 = 1;
 * @return {?proto.dstore.values.booleanValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getSortOrder1 = function() {
  return /** @type{?proto.dstore.values.booleanValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.booleanValue, 1));
};


/** @param {?proto.dstore.values.booleanValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setSortOrder1 = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.clearSortOrder1 = function() {
  this.setSortOrder1(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.hasSortOrder1 = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool sort_order1_null = 1001;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getSortOrder1Null = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1001, false));
};


/** @param {boolean} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setSortOrder1Null = function(value) {
  jspb.Message.setField(this, 1001, value);
};


/**
 * optional dstore.values.booleanValue sort_order2 = 2;
 * @return {?proto.dstore.values.booleanValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getSortOrder2 = function() {
  return /** @type{?proto.dstore.values.booleanValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.booleanValue, 2));
};


/** @param {?proto.dstore.values.booleanValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setSortOrder2 = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.clearSortOrder2 = function() {
  this.setSortOrder2(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.hasSortOrder2 = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool sort_order2_null = 1002;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getSortOrder2Null = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1002, false));
};


/** @param {boolean} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setSortOrder2Null = function(value) {
  jspb.Message.setField(this, 1002, value);
};


/**
 * optional dstore.values.booleanValue sort_order3 = 3;
 * @return {?proto.dstore.values.booleanValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getSortOrder3 = function() {
  return /** @type{?proto.dstore.values.booleanValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.booleanValue, 3));
};


/** @param {?proto.dstore.values.booleanValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setSortOrder3 = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.clearSortOrder3 = function() {
  this.setSortOrder3(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.hasSortOrder3 = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional bool sort_order3_null = 1003;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getSortOrder3Null = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1003, false));
};


/** @param {boolean} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setSortOrder3Null = function(value) {
  jspb.Message.setField(this, 1003, value);
};


/**
 * optional dstore.values.stringValue output_characteristic_ids = 4;
 * @return {?proto.dstore.values.stringValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getOutputCharacteristicIds = function() {
  return /** @type{?proto.dstore.values.stringValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.stringValue, 4));
};


/** @param {?proto.dstore.values.stringValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setOutputCharacteristicIds = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.clearOutputCharacteristicIds = function() {
  this.setOutputCharacteristicIds(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.hasOutputCharacteristicIds = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bool output_characteristic_ids_null = 1004;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getOutputCharacteristicIdsNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1004, false));
};


/** @param {boolean} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setOutputCharacteristicIdsNull = function(value) {
  jspb.Message.setField(this, 1004, value);
};


/**
 * optional dstore.values.integerValue count = 5;
 * @return {?proto.dstore.values.integerValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getCount = function() {
  return /** @type{?proto.dstore.values.integerValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.integerValue, 5));
};


/** @param {?proto.dstore.values.integerValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setCount = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.clearCount = function() {
  this.setCount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.hasCount = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bool count_null = 1005;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getCountNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1005, false));
};


/** @param {boolean} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setCountNull = function(value) {
  jspb.Message.setField(this, 1005, value);
};


/**
 * optional dstore.values.integerValue person_type_id = 6;
 * @return {?proto.dstore.values.integerValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getPersonTypeId = function() {
  return /** @type{?proto.dstore.values.integerValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.integerValue, 6));
};


/** @param {?proto.dstore.values.integerValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setPersonTypeId = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.clearPersonTypeId = function() {
  this.setPersonTypeId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.hasPersonTypeId = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional bool person_type_id_null = 1006;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getPersonTypeIdNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1006, false));
};


/** @param {boolean} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setPersonTypeIdNull = function(value) {
  jspb.Message.setField(this, 1006, value);
};


/**
 * optional dstore.values.stringValue last_values = 7;
 * @return {?proto.dstore.values.stringValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getLastValues = function() {
  return /** @type{?proto.dstore.values.stringValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.stringValue, 7));
};


/** @param {?proto.dstore.values.stringValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setLastValues = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.clearLastValues = function() {
  this.setLastValues(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.hasLastValues = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional bool last_values_null = 1007;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getLastValuesNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1007, false));
};


/** @param {boolean} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setLastValuesNull = function(value) {
  jspb.Message.setField(this, 1007, value);
};


/**
 * optional dstore.values.integerValue last_person_id = 8;
 * @return {?proto.dstore.values.integerValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getLastPersonId = function() {
  return /** @type{?proto.dstore.values.integerValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.integerValue, 8));
};


/** @param {?proto.dstore.values.integerValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setLastPersonId = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.clearLastPersonId = function() {
  this.setLastPersonId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.hasLastPersonId = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional bool last_person_id_null = 1008;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getLastPersonIdNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1008, false));
};


/** @param {boolean} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setLastPersonIdNull = function(value) {
  jspb.Message.setField(this, 1008, value);
};


/**
 * optional dstore.values.booleanValue next = 9;
 * @return {?proto.dstore.values.booleanValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getNext = function() {
  return /** @type{?proto.dstore.values.booleanValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.booleanValue, 9));
};


/** @param {?proto.dstore.values.booleanValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setNext = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.clearNext = function() {
  this.setNext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.hasNext = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional bool next_null = 1009;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getNextNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1009, false));
};


/** @param {boolean} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setNextNull = function(value) {
  jspb.Message.setField(this, 1009, value);
};


/**
 * optional dstore.values.integerValue row_number = 10;
 * @return {?proto.dstore.values.integerValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getRowNumber = function() {
  return /** @type{?proto.dstore.values.integerValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.integerValue, 10));
};


/** @param {?proto.dstore.values.integerValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setRowNumber = function(value) {
  jspb.Message.setWrapperField(this, 10, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.clearRowNumber = function() {
  this.setRowNumber(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.hasRowNumber = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional bool row_number_null = 1010;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getRowNumberNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1010, false));
};


/** @param {boolean} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setRowNumberNull = function(value) {
  jspb.Message.setField(this, 1010, value);
};


/**
 * optional dstore.values.integerValue group_id = 11;
 * @return {?proto.dstore.values.integerValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getGroupId = function() {
  return /** @type{?proto.dstore.values.integerValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.integerValue, 11));
};


/** @param {?proto.dstore.values.integerValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setGroupId = function(value) {
  jspb.Message.setWrapperField(this, 11, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.clearGroupId = function() {
  this.setGroupId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.hasGroupId = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional bool group_id_null = 1011;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getGroupIdNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1011, false));
};


/** @param {boolean} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setGroupIdNull = function(value) {
  jspb.Message.setField(this, 1011, value);
};


/**
 * optional dstore.values.stringValue characteristic_id_list = 12;
 * @return {?proto.dstore.values.stringValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getCharacteristicIdList = function() {
  return /** @type{?proto.dstore.values.stringValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.stringValue, 12));
};


/** @param {?proto.dstore.values.stringValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setCharacteristicIdList = function(value) {
  jspb.Message.setWrapperField(this, 12, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.clearCharacteristicIdList = function() {
  this.setCharacteristicIdList(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.hasCharacteristicIdList = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional bool characteristic_id_list_null = 1012;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getCharacteristicIdListNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1012, false));
};


/** @param {boolean} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setCharacteristicIdListNull = function(value) {
  jspb.Message.setField(this, 1012, value);
};


/**
 * optional dstore.values.stringValue condition_list = 13;
 * @return {?proto.dstore.values.stringValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getConditionList = function() {
  return /** @type{?proto.dstore.values.stringValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.stringValue, 13));
};


/** @param {?proto.dstore.values.stringValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setConditionList = function(value) {
  jspb.Message.setWrapperField(this, 13, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.clearConditionList = function() {
  this.setConditionList(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.hasConditionList = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional bool condition_list_null = 1013;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getConditionListNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1013, false));
};


/** @param {boolean} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setConditionListNull = function(value) {
  jspb.Message.setField(this, 1013, value);
};


/**
 * optional dstore.values.stringValue country = 14;
 * @return {?proto.dstore.values.stringValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getCountry = function() {
  return /** @type{?proto.dstore.values.stringValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.stringValue, 14));
};


/** @param {?proto.dstore.values.stringValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setCountry = function(value) {
  jspb.Message.setWrapperField(this, 14, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.clearCountry = function() {
  this.setCountry(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.hasCountry = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional bool country_null = 1014;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getCountryNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1014, false));
};


/** @param {boolean} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setCountryNull = function(value) {
  jspb.Message.setField(this, 1014, value);
};


/**
 * optional dstore.values.integerValue output_into_one_id = 15;
 * @return {?proto.dstore.values.integerValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getOutputIntoOneId = function() {
  return /** @type{?proto.dstore.values.integerValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.integerValue, 15));
};


/** @param {?proto.dstore.values.integerValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setOutputIntoOneId = function(value) {
  jspb.Message.setWrapperField(this, 15, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.clearOutputIntoOneId = function() {
  this.setOutputIntoOneId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.hasOutputIntoOneId = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional bool output_into_one_id_null = 1015;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getOutputIntoOneIdNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1015, false));
};


/** @param {boolean} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setOutputIntoOneIdNull = function(value) {
  jspb.Message.setField(this, 1015, value);
};


/**
 * optional dstore.values.stringValue separator_in_last_values = 16;
 * @return {?proto.dstore.values.stringValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getSeparatorInLastValues = function() {
  return /** @type{?proto.dstore.values.stringValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.stringValue, 16));
};


/** @param {?proto.dstore.values.stringValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setSeparatorInLastValues = function(value) {
  jspb.Message.setWrapperField(this, 16, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.clearSeparatorInLastValues = function() {
  this.setSeparatorInLastValues(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.hasSeparatorInLastValues = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional bool separator_in_last_values_null = 1016;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getSeparatorInLastValuesNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1016, false));
};


/** @param {boolean} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setSeparatorInLastValuesNull = function(value) {
  jspb.Message.setField(this, 1016, value);
};


/**
 * optional dstore.values.stringValue separator_in_condition_list = 17;
 * @return {?proto.dstore.values.stringValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getSeparatorInConditionList = function() {
  return /** @type{?proto.dstore.values.stringValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.stringValue, 17));
};


/** @param {?proto.dstore.values.stringValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setSeparatorInConditionList = function(value) {
  jspb.Message.setWrapperField(this, 17, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.clearSeparatorInConditionList = function() {
  this.setSeparatorInConditionList(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.hasSeparatorInConditionList = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional bool separator_in_condition_list_null = 1017;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.getSeparatorInConditionListNull = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1017, false));
};


/** @param {boolean} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Parameters.prototype.setSeparatorInConditionListNull = function(value) {
  jspb.Message.setField(this, 1017, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.repeatedFields_, null);
};
goog.inherits(proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.displayName = 'proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.repeatedFields_ = [2,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.prototype.toObject = function(opt_includeInstance) {
  return proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response} msg The msg instance to transform.
 * @return {!Object}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.toObject = function(includeInstance, msg) {
  var f, obj = {
    metaInformationList: jspb.Message.toObjectList(msg.getMetaInformationList(),
    dstore_engine_metainformation_pb.MetaInformation.toObject, includeInstance),
    messageList: jspb.Message.toObjectList(msg.getMessageList(),
    dstore_engine_message_pb.Message.toObject, includeInstance),
    rowList: jspb.Message.toObjectList(msg.getRowList(),
    proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.toObject, includeInstance),
    count: (f = msg.getCount()) && dstore_values_pb.integerValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response;
  return proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new dstore_engine_metainformation_pb.MetaInformation;
      reader.readMessage(value,dstore_engine_metainformation_pb.MetaInformation.deserializeBinaryFromReader);
      msg.addMetaInformation(value);
      break;
    case 3:
      var value = new dstore_engine_message_pb.Message;
      reader.readMessage(value,dstore_engine_message_pb.Message.deserializeBinaryFromReader);
      msg.addMessage(value);
      break;
    case 4:
      var value = new proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row;
      reader.readMessage(value,proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.deserializeBinaryFromReader);
      msg.addRow(value);
      break;
    case 101:
      var value = new dstore_values_pb.integerValue;
      reader.readMessage(value,dstore_values_pb.integerValue.deserializeBinaryFromReader);
      msg.setCount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getMetaInformationList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      dstore_engine_metainformation_pb.MetaInformation.serializeBinaryToWriter
    );
  }
  f = this.getMessageList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      dstore_engine_message_pb.Message.serializeBinaryToWriter
    );
  }
  f = this.getRowList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.serializeBinaryToWriter
    );
  }
  f = this.getCount();
  if (f != null) {
    writer.writeMessage(
      101,
      f,
      dstore_values_pb.integerValue.serializeBinaryToWriter
    );
  }
};


/**
 * repeated dstore.engine.metainformation.MetaInformation meta_information = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.dstore.engine.metainformation.MetaInformation>}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.prototype.getMetaInformationList = function() {
  return /** @type{!Array.<!proto.dstore.engine.metainformation.MetaInformation>} */ (
    jspb.Message.getRepeatedWrapperField(this, dstore_engine_metainformation_pb.MetaInformation, 2));
};


/** @param {!Array.<!proto.dstore.engine.metainformation.MetaInformation>} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.prototype.setMetaInformationList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.dstore.engine.metainformation.MetaInformation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.dstore.engine.metainformation.MetaInformation}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.prototype.addMetaInformation = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.dstore.engine.metainformation.MetaInformation, opt_index);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.prototype.clearMetaInformationList = function() {
  this.setMetaInformationList([]);
};


/**
 * repeated dstore.engine.message.Message message = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.dstore.engine.message.Message>}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.prototype.getMessageList = function() {
  return /** @type{!Array.<!proto.dstore.engine.message.Message>} */ (
    jspb.Message.getRepeatedWrapperField(this, dstore_engine_message_pb.Message, 3));
};


/** @param {!Array.<!proto.dstore.engine.message.Message>} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.prototype.setMessageList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.dstore.engine.message.Message=} opt_value
 * @param {number=} opt_index
 * @return {!proto.dstore.engine.message.Message}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.prototype.addMessage = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.dstore.engine.message.Message, opt_index);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.prototype.clearMessageList = function() {
  this.setMessageList([]);
};


/**
 * repeated Row row = 4;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row>}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.prototype.getRowList = function() {
  return /** @type{!Array.<!proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row, 4));
};


/** @param {!Array.<!proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row>} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.prototype.setRowList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row=} opt_value
 * @param {number=} opt_index
 * @return {!proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.prototype.addRow = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row, opt_index);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.prototype.clearRowList = function() {
  this.setRowList([]);
};


/**
 * optional dstore.values.integerValue count = 101;
 * @return {?proto.dstore.values.integerValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.prototype.getCount = function() {
  return /** @type{?proto.dstore.values.integerValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.integerValue, 101));
};


/** @param {?proto.dstore.values.integerValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.prototype.setCount = function(value) {
  jspb.Message.setWrapperField(this, 101, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.prototype.clearCount = function() {
  this.setCount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.prototype.hasCount = function() {
  return jspb.Message.getField(this, 101) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.displayName = 'proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.toObject = function(opt_includeInstance) {
  return proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row} msg The msg instance to transform.
 * @return {!Object}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.toObject = function(includeInstance, msg) {
  var f, obj = {
    rowId: jspb.Message.getFieldWithDefault(msg, 10000, 0),
    personId: (f = msg.getPersonId()) && dstore_values_pb.integerValue.toObject(includeInstance, f),
    value1: (f = msg.getValue1()) && dstore_values_pb.stringValue.toObject(includeInstance, f),
    value2: (f = msg.getValue2()) && dstore_values_pb.stringValue.toObject(includeInstance, f),
    value3: (f = msg.getValue3()) && dstore_values_pb.stringValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row;
  return proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 10000:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRowId(value);
      break;
    case 10001:
      var value = new dstore_values_pb.integerValue;
      reader.readMessage(value,dstore_values_pb.integerValue.deserializeBinaryFromReader);
      msg.setPersonId(value);
      break;
    case 20002:
      var value = new dstore_values_pb.stringValue;
      reader.readMessage(value,dstore_values_pb.stringValue.deserializeBinaryFromReader);
      msg.setValue1(value);
      break;
    case 30003:
      var value = new dstore_values_pb.stringValue;
      reader.readMessage(value,dstore_values_pb.stringValue.deserializeBinaryFromReader);
      msg.setValue2(value);
      break;
    case 40002:
      var value = new dstore_values_pb.stringValue;
      reader.readMessage(value,dstore_values_pb.stringValue.deserializeBinaryFromReader);
      msg.setValue3(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getRowId();
  if (f !== 0) {
    writer.writeInt32(
      10000,
      f
    );
  }
  f = this.getPersonId();
  if (f != null) {
    writer.writeMessage(
      10001,
      f,
      dstore_values_pb.integerValue.serializeBinaryToWriter
    );
  }
  f = this.getValue1();
  if (f != null) {
    writer.writeMessage(
      20002,
      f,
      dstore_values_pb.stringValue.serializeBinaryToWriter
    );
  }
  f = this.getValue2();
  if (f != null) {
    writer.writeMessage(
      30003,
      f,
      dstore_values_pb.stringValue.serializeBinaryToWriter
    );
  }
  f = this.getValue3();
  if (f != null) {
    writer.writeMessage(
      40002,
      f,
      dstore_values_pb.stringValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 row_id = 10000;
 * @return {number}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.getRowId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10000, 0));
};


/** @param {number} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.setRowId = function(value) {
  jspb.Message.setField(this, 10000, value);
};


/**
 * optional dstore.values.integerValue person_id = 10001;
 * @return {?proto.dstore.values.integerValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.getPersonId = function() {
  return /** @type{?proto.dstore.values.integerValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.integerValue, 10001));
};


/** @param {?proto.dstore.values.integerValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.setPersonId = function(value) {
  jspb.Message.setWrapperField(this, 10001, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.clearPersonId = function() {
  this.setPersonId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.hasPersonId = function() {
  return jspb.Message.getField(this, 10001) != null;
};


/**
 * optional dstore.values.stringValue value1 = 20002;
 * @return {?proto.dstore.values.stringValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.getValue1 = function() {
  return /** @type{?proto.dstore.values.stringValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.stringValue, 20002));
};


/** @param {?proto.dstore.values.stringValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.setValue1 = function(value) {
  jspb.Message.setWrapperField(this, 20002, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.clearValue1 = function() {
  this.setValue1(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.hasValue1 = function() {
  return jspb.Message.getField(this, 20002) != null;
};


/**
 * optional dstore.values.stringValue value2 = 30003;
 * @return {?proto.dstore.values.stringValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.getValue2 = function() {
  return /** @type{?proto.dstore.values.stringValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.stringValue, 30003));
};


/** @param {?proto.dstore.values.stringValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.setValue2 = function(value) {
  jspb.Message.setWrapperField(this, 30003, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.clearValue2 = function() {
  this.setValue2(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.hasValue2 = function() {
  return jspb.Message.getField(this, 30003) != null;
};


/**
 * optional dstore.values.stringValue value3 = 40002;
 * @return {?proto.dstore.values.stringValue}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.getValue3 = function() {
  return /** @type{?proto.dstore.values.stringValue} */ (
    jspb.Message.getWrapperField(this, dstore_values_pb.stringValue, 40002));
};


/** @param {?proto.dstore.values.stringValue|undefined} value */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.setValue3 = function(value) {
  jspb.Message.setWrapperField(this, 40002, value);
};


proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.clearValue3 = function() {
  this.setValue3(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.dstore.engine.pm_GetPersons_Conditions_Ad.Response.Row.prototype.hasValue3 = function() {
  return jspb.Message.getField(this, 40002) != null;
};


goog.object.extend(exports, proto.dstore.engine.pm_GetPersons_Conditions_Ad);
